# Generated by Django 2.2.7 on 2019-11-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_link', models.CharField(max_length=200)),
                ('describe_link', models.TextField()),
                ('free_test', models.BooleanField(default=True)),
                ('personal_proxy', models.BooleanField(default=True)),
                ('change_proxy', models.BooleanField(default=True)),
            ],
        ),
    ]
