# Generated by Django 2.2.7 on 2019-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referer',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
