# Generated by Django 2.2.7 on 2019-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pages', '0002_referer_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='referer',
            name='img',
            field=models.ImageField(default='my_site/ref_pages/templates/img/q12.jpg', upload_to='my_site/ref_pages/templates/ref_pages/img'),
        ),
    ]
