# Generated by Django 2.2.7 on 2019-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_pages', '0005_auto_20191118_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referer',
            name='img',
            field=models.ImageField(default='img/q12.jpg', upload_to='img'),
        ),
    ]
