# Generated by Django 2.2.2 on 2019-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_persone', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(verbose_name='date published')),
                ('name_persone', models.CharField(max_length=200)),
            ],
        ),
    ]
