# Generated by Django 2.2.2 on 2019-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_phonebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diz_top', models.IntegerField(default=0)),
                ('tank_amm', models.IntegerField(default=23)),
                ('tank_name', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('crew', models.IntegerField(default=3)),
            ],
        ),
    ]
