# Generated by Django 2.2.2 on 2019-06-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poll.Article')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
