# Generated by Django 2.2.3 on 2019-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190626_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserAgent', models.TextField()),
                ('IP_user', models.CharField(max_length=50)),
            ],
        ),
    ]
