# Generated by Django 2.2.3 on 2019-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=0, upload_to='catalog_images'),
            preserve_default=False,
        ),
    ]
