# Generated by Django 2.2.7 on 2019-11-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20190805_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
